coverage_service: cobertura_xml
output_directory: xml_report
xcodeproj: FashionStore.xcodeproj
workspace: FashionStore.xcworkspace
scheme: FashionStore
configuration: Debug
source_directory: FashionStore
binary_basename: FashionStore
ignore:
  - Pods/*
  - FashionStoreTests/*
  - FashionStoreUITests/*
