# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9.3beta
language: swift
# cache: cocoapods
# podfile: Example/Podfile
before_install: 
  - rvm use $RVM_RUBY_VERSION
  - gem install cocoapods # Since Travis is not always on latest version
  - pod repo update
  - pod install --verbose
after_success: 
  - bash <(curl -s https://codecov.io/bash) -X coveragepy -X gcov -t ba92fd5d-4148-4a70-ac23-f2eaa4da6c19
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace FashionStore.xcworkspace -scheme FashionStore -sdk iphonesimulator11.2 -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.2' ONLY_ACTIVE_ARCH=YES VALID_ARCHS=x86_64 | xcpretty
