# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9.2
language: swift
# cache: cocoapods
# podfile: Example/Podfile
before_install: 
  - rvm use $RVM_RUBY_VERSION
  - gem install cocoapods # Since Travis is not always on latest version
  - pod repo update
  - pod install --verbose
install: 
  - gem install slather --no-rdoc --no-ri --no-document --quiet
after_success: 
  - slather
  - bash <(curl -s https://codecov.io/bash) -t ba92fd5d-4148-4a70-ac23-f2eaa4da6c19
script:
- xcodebuild -scheme FashionStore -workspace FashionStore.xcworkspace -sdk iphonesimulator11.2 -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.2' ONLY_ACTIVE_ARCH=YES VALID_ARCHS=x86_64 build test